### ISSUE TITLE
Subsystems vs SubsystemContainer vs RobotContainer vs alternative?

### ISSUE THREAD

**Issue by 1198159** [robototes/RapidReact2022#11]
which one do we use I dont like any of the three options

**Comment by TAKBS2412** [comment]
RobotContainer matches the WPILib documentation, so that would be helpful for other teams/incoming members.

However, it's not the most descriptive, so there's certainly a good case for the other names.

**Comment by SumedhP** [comment]
Subsystems is fine, we just need to keep the folder singular
