### ISSUE TITLE
Tune Anti-Tip

### ISSUE THREAD

**Issue by obj-obj** [robototes/RapidReact2022#118]
We should have some sort of anti-tip code that uses the gyro to detect when the robot is falling over, and uses the drivebase to compensate (by driving in the same direction as the tipping) to prevent the robot from falling over. Joseph said there was already some anti-tip code, so maybe we should improve it

**Comment by obj-obj** [comment]
Also, if the current anti-tip code can't be improved, we should do some testing to tune the constants better (if there are any constants to be tuned)

**Comment by obj-obj** [comment]
There's already anti-tip code, so this issue should be about tuning instead

**Comment by 1198159** [comment]
with the changes made to height of shooter anti tip will need retune, also added accel limits to drive per my pr

**Comment by 1198159** [comment]
can tune day of comp dwai
