### ISSUE TITLE
Get shooter fully working (aiming while moving)

### ISSUE THREAD

**Issue by obj-obj** [robototes/RapidReact2022#119]
This would involve fixing the soft limits on the turret, and a lot of testing/improving code to get shooter to the point that it can aim and shoot while the robot is moving. Also an automatic shooting mode should be added, if possible

Another thing that might be useful is slowly rotating the turret when limelight doesn't see anything, in order to lock on to the hub (this would all be disableable by drive team, of course)

**Comment by 1198159** [comment]
working on it see my pr

**Comment by obj-obj** [comment]
wait noooo I wanted to do it on friday

**Comment by 1198159** [comment]
i probably need 1 rat to tune the data points with new shooter and 2 rats for feedforward i hope i can get this.
