### ISSUE TITLE
Should commands be refactored to not require subsystems to be passed in?

### ISSUE THREAD

**Issue by obj-obj** [robototes/RapidReact2022#121]
Some good solutions would be either passing around the subsystems class instead or converting the subsystem to static constants so commands can just import the constants class

**Comment by obj-obj** [comment]
Actually making everything a singleton is a better idea

**Comment by 1198159** [comment]
is this really an issue though?

**Comment by obj-obj** [comment]
It's just kind of annoying to keep passing subsystem to commands so I was thinking singletons + doc comments would be a better idea

**Comment by obj-obj** [comment]
I will put my reasoning from the PR here:

I don't think removing the subsystem arguments from command is an issue, because doc comments show up just fine on vscode's autocomplete/hover, allowing you to still easily see what subsystems a command uses. Also, isn't this what documentation is for..?
The main reason I want this change is because it's just annoying to have to pass in multiple subsystems when running some commands (it's just extra boilerplate).
As for reviewing PRs, just install the GitHub extension in vscode, then go to the github tab on the sidebar and right click one of the PRs -> Checkout pull request.

How the doc comments look in vscode (autocomplete & hover):
https://user-images.githubusercontent.com/57120300/157323415-3f033069-81d2-40a0-949c-7e68508f9906.png
https://user-images.githubusercontent.com/57120300/157323686-babd7b59-809e-406c-91e4-6499b01f441d.png
