### ISSUE TITLE
Hardware and subsystems initialization runs before H/W is ready 

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/RapidReact2022#30]
The hardware, subsystems, and control initialization currently happens at process start, which sometimes is before the physical hardware is ready to be used. They should move to robotInit so they don't race with physical hardware setup.

**Comment by jbko6** [comment]
Would it make sense to initialize controls at teleop init instead of robot init?

**Comment by jamesdooley4** [comment]
Probably not, as the code would have to make sure the controls don't get re-initialized the 2nd time teleop init is called (enable -> disable -> enable). And the controls themselves should protect against being used if the robot's not enabled in teleop mode.
