### ISSUE TITLE
Add code format PR check

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/RapidReact2022#37]
@obj-obj - If we move to the Google format standard, it looks like https://github.com/marketplace/actions/google-java-format could be setup as an action to check formatting & block PRs until it's fixed. Does the checked-in eclipse-formatter.xml (used by the VSCode Java formatter) match the Google format rules?  If not, can you update it so it does, or recommend another VSCode plugin that school laptops can use to trivially format code?

**Comment by obj-obj** [comment]
@jamesdooley4 https://github.com/diffplug/spotless/tree/main/plugin-gradle might work, assuming it follows the same standard that java support for vs code does. I'll make a new branch, install it, and see if it finds any violations in the repository right now (as it's already formatted)

**Comment by obj-obj** [comment]
Spotless has support for the Eclipse standard, which is what we are using currently

**Comment by obj-obj** [comment]
PR time
